# Generated by Django 4.2.6 on 2023-10-29 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_contact_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='state',
        ),
        migrations.RemoveField(
            model_name='room',
            name='state',
        ),
        migrations.RemoveField(
            model_name='user',
            name='state',
        ),
    ]
