# Generated by Django 4.2.6 on 2023-10-29 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_house_state_remove_room_state_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('body', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name': 'Review',
                'db_table': 'review',
            },
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
